deneme/Controllers/AboutController.cs
using deneme.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;

namespace deneme.Controllers
{
    public class AboutController : Controller
    {
        public readonly BlogPostDbContext _db; 

        public AboutController(BlogPostDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<About> list = _db.Abouts.ToList();
            return View(list);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var post = _db.Abouts.Find(id);
            if (post == null)
            {
                return NotFound();
            }
            return View(post);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(About obj)
        {
            if (ModelState.IsValid)
            {
                _db.Abouts.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }



    }
}

deneme/Controllers/AdminController.cs
using deneme.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace deneme.Controllers
{
    public class AdminController : Controller
    {
        //Admin / Post Controller 
        public readonly BlogPostDbContext _db;

        public AdminController(BlogPostDbContext db)
        {
            _db = db;
        }

        public int getLength()
        {
            if(_db.TblPosts == null)
            {
                return 0; 
            }
            var length = _db.TblPosts.ToArray().Length;
            return length;
        }


        [Authorize]
        public IActionResult Index()
        {
            var postNumber = getLength();
            return View(postNumber);
        }


        public IActionResult Listele()
        {
            IEnumerable<TblPost> objCategoryList = _db.TblPosts.ToList();
            return View(objCategoryList);
        }

        //Create new post
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(TblPost obj)
        {
            if (ModelState.IsValid)
            {
                _db.TblPosts.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Listele");
            }
            return View(obj);
        }
        //Edit post 
        public IActionResult Edit(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }
            var post = _db.TblPosts.Find(id);
            if(post == null)
            {
                return NotFound();
            }
            return View(post);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(TblPost post)
        {
            if (ModelState.IsValid)
            {
                post.UpdatedTime = DateTime.Now;
                post.CreatedTime = DateTime.Now;//TODO: created time update time ile ayni
                _db.TblPosts.Update(post);
                _db.SaveChanges();
                return RedirectToAction("Listele");
            }
            return View(post);
        }

        //Delete Post
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var post = _db.TblPosts.Find(id);
            if (post == null)
            {
                return NotFound();
            }
            return View(post);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _db.TblPosts.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _db.TblPosts.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Listele");
        }

        //See Details of a post
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _db.TblPosts == null)
            {
                return NotFound();
            }

            var tblPost = await _db.TblPosts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tblPost == null)
            {
                return NotFound();
            }

            return View(tblPost);
        }





    }
}

deneme/Views/Admin/Create.cshtml
@model TblPost
@{
    ViewData["Title"] = "Create";
}



<h1>Create</h1>


<form method="post" asp-action="Create">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create A Post</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Title">Title</label>
            <input asp-for="Title" class="form-control">
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Body">Body</label>
           
            <textarea asp-for="Body" id="body" class="form-control" style="height:200px"></textarea>
            <span asp-validation-for="Body" class="text-danger"></span>
        </div>
             <div class="mb-3">
            <label asp-for="PostResim">Image</label>
            <input asp-for="PostResim" class="form-control" style="height:200px">
            <span asp-validation-for="PostResim" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a asp-controller="Admin" asp-action="Listele" class="btn btn-secondary" style="width:150px">
            Back To List
        </a>
    </div>
</form>

deneme/Views/Admin/Delete.cshtml
@model TblPost

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>



<form method="post" asp-action="DeletePost">

    <input asp-for="Id" hidden>

    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete Post</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Title"></label>
            <input asp-for="Title" disabled class="form-control">
        </div>
        <div class="mb-3">
            <label asp-for="Body"></label>
            <input asp-for="Body" disabled class="form-control">

        </div>
        <button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
        <a asp-controller="Admin" asp-action="Listele" class="btn btn-secondary" style="width:150px">
            Back To List
        </a>
    </div>


</form>

deneme/Views/Admin/Details.cshtml
@model deneme.Models.TblPost
@{
    ViewData["Title"] = "Details";
}

<style>
    #resim {
        max-width: 400px;
    }
</style>
<h1>Details</h1>

<div>
    <h4>TblPost</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Body)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Body)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedTime)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UpdatedTime)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PostResim)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PostResim)
        </dd>
        <img id="resim"src=@Html.DisplayFor(model => model.PostResim)>

    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Listele">Back to List</a>
</div>

deneme/Views/Admin/Edit.cshtml
@model TblPost
@{
    ViewData["Title"] = "Edit";
}
<style>
    #resim {
        max-width: 400px;
    }
</style>
<h1>Edit</h1>

<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Post</h2>
            <hr />
        </div>
       
        <div class="mb-3">
            <label asp-for="Title">Name</label>
            <input asp-for="Title" class="form-control">
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        
        <div class="mb-3">
            <label asp-for="Body">Body</label>
            <textarea asp-for="Body" id="body" class="form-control"></textarea>
            <span asp-validation-for="Body" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="PostResim">Image</label>
            <input asp-for="PostResim" class="form-control">
            <span asp-validation-for="PostResim" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
        <a asp-controller="Admin" asp-action="Listele" class="btn btn-secondary" style="width:150px">
            Back To List
        </a>
    </div>
</form>

<div>
    <p> Post Image:</p>
    <img id="resim" src=@Model.PostResim/>

</div>

deneme/Views/Admin/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<script src="../_vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="../_vendor/prismjs/prism.js"></script>
<script src="../_assets/js/custom.js"></script>


<style>
    .btn{
        height:250px; 
        width:300px;
        background-color:white;
        color:black;
        text-align:center;
    }
    body{
        background-color:black;
    }

   #shdw3:hover,#shdw4:hover{

        box-shadow: 5px 5px 5px 2px white;
    }
    
</style>

<div class="container">
    <div class="row">
        <div class="col-md-3">
             <a class="btn btn-outline-light mx-2" id="shdw1" >
                <i class="bi bi-pencil-square"></i>&nbsp; Gunluk ziyaretci sayisi:
            </a>
        </div>
        <div class="col-md-3">
            <a class="btn btn-outline-light" id="shdw2">
                <p style="text-align:center;"><i class="bi bi-pencil-square"></i>&nbsp; Toplam Post Sayisi: <p style="font-size:50px;">@Model</p></p>
            </a>
        </div>
        <div class="col-md-3">
            <a asp-controller="About" asp-action="Index" asp-route-id="" class="btn btn-outline-light" id="shdw3">
                <i class="bi bi-pencil-square"></i>&nbsp; Manage About Page:
            </a>
 
        </div>
        <div class="col-md-3">
            <a asp-controller="Admin" asp-action="Listele" asp-route-id="" class="btn btn-outline-light" id="shdw4">
                <i class="bi bi-pencil-square"></i>&nbsp; Manage Posts:
            </a>
        </div>

</div>
</div>

deneme/Views/Admin/Listele.cshtml
@model IEnumerable<TblPost>
@{
    ViewData["Title"] = "Listele";
}

<!-- Metnin aciklamasi fazla uzunsa onu keser, sadece bir kismini alir.-->
@{
    var bodyText = new Dictionary<TblPost, string>(); 
    foreach(var obj in Model){
        if(obj.Body != null){
            if (obj.Body.Length > 35)
            {
                bodyText.Add(obj, obj.Body.ToString().Substring(0, 35) + "...");
            }
            else
            {
                bodyText.Add(obj, obj.Body.ToString());
            }
        }
        else {
            bodyText[obj] = " ";
        }

    }



}

<h1>Manage Posts</h1>


<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2>Post List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Admin" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> &nbsp; Create New Post
            </a>
        </div>
    </div>
    <br>
    <br>


    <table class="table table-bordered table-striped" id="fnd1">
        <thead>
            <tr>
                <th>
                    Post Id
                </th>
                <th>
                    Post Title
                </th>
                <th>
                    Post Body
                </th>
                <th>
                    Created Time
                </th>
                <th>

                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td width="10%">
                        @obj.Id
                    </td>
                    <td width="30%">
                        @obj.Title
                    </td>
                    <td width="20%">
                        @bodyText[obj]
                    </td>
                    <td width="20%">
                        @obj.CreatedTime
                    </td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Admin" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-primary mx-2">
                                <i class="bi bi-pencil-square"></i>&nbsp; Edit
                            </a>
                            <a asp-controller="Admin" asp-action="Details" asp-route-id="@obj.Id" class="btn btn-primary mx-2">
                                <i class="bi bi-pencil-square"></i>&nbsp; Details
                            </a>
                            <a asp-controller="Admin" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger mx-2">Delete</a>
                        </div>
                    </td>
                </tr>
            }

        </tbody>
    </table>
</div>

@section scripts{
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.12.1/af-2.4.0/datatables.min.css" />

    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.12.1/af-2.4.0/datatables.min.js"></script>

    <script>
        $(document).ready(function () {
            $("#fnd1").DataTable();

        });
    </script>

}